services:
  fuelgo-webapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODE_TYPE: Development
      ASPNETCORE_ENVIRONMENT: Development
      REDIS_HOST: redis:6379
      ApiSettings__TankApiKey: ${TANK_API_KEY}
      ApiSettings__OpenRouteServiceApiKey: ${OPENROUTESERVICE_API_KEY}

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - fuelgo-webapp