name: CI + Build + Nightly Deploy

on:
  push:
    branches: ["master"]

  pull_request:

  schedule:
    - cron: "0 1 * * *"

  workflow_dispatch:

permissions:
  contents: read
  packages: write

# -------------------------
# 1. TESTS (immer)
# -------------------------
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - run: dotnet test --configuration Release

# -------------------------
# 2. BUILD (nur wenn master OR nightly OR manual)
# -------------------------
  build:
    needs: test
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    outputs:
      image_tag: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v5

      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build & Push
        run: |
          docker build -t ghcr.io/otto1999haertel/fueldistancecalculator:${{ github.sha }} .
          docker push ghcr.io/otto1999haertel/fueldistancecalculator:${{ github.sha }}

# -------------------------
# 3. DEPLOY (nur Nightly + Manual)
# -------------------------
  deploy:
    needs: build
    runs-on: ubuntu-latest

    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -e

          cd /home/${{ secrets.SSH_USER }}/fuelgo

          echo "Pull latest image"

          docker pull ghcr.io/otto1999haertel/fueldistancecalculator:${{ needs.build.outputs.image_tag }}

          IMAGE_TAG=${{ needs.build.outputs.image_tag }} docker compose --env-file .env.server up -d --no-deps --force-recreate fuelgo-webapp
          EOF