name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - run: dotnet build --configuration Release

  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      TANK_API_KEY: ${{ secrets.TANKAPIKEY }}
      OPENROUTESERVICE_API_KEY: ${{ secrets.OPENROUTESERVICEAPIKEY }}
    steps:
      - uses: actions/checkout@v5
      - run: dotnet test --configuration Release